*** Variables ***
${UsernameInput}                 xpath://input[@name='username']
${UsernameInputCss}              css:input[name='username']
${PasswordInput}                 xpath://input[@name='password']
${PasswordInputCss}              css:input[name='password']
${LoginButton}                   xpath://button[@type='submit']
${LoginButtonCss}                css:button[type='submit']
${ForgotPasswordLink}            xpath://p[contains(@class,'orangehrm-login-forgot-header')]
${DashboardHeader}               xpath://h6[normalize-space()='Dashboard']
${ProfileMenu}                   xpath://span[contains(@class,'oxd-userdropdown-tab')]
${LogoutLink}                    xpath://a[normalize-space()='Logout']
${InvalidCredentialsError}       xpath://p[contains(@class,'oxd-alert-content-text') and contains(.,'Invalid credentials')]
${RequiredFieldValidation}       xpath://span[normalize-space()='Required']
${ResetPasswordHeader}           xpath://h6[normalize-space()='Reset Password']
${ResetPasswordButton}           xpath://button[@type='submit']
${ResetPasswordSuccessMessage}   xpath://*[contains(normalize-space(.),'Reset Password link sent successfully')]
${PimMenu}                       xpath://span[normalize-space()='PIM']
${PimMenuLink}                   xpath://a[contains(@href,'/pim/viewPimModule')]
${PimMenuLinkCss}                css:a[href*='/pim/viewPimModule']
${PimHeader}                     xpath://h6[normalize-space()='PIM']
${LoginPageHeader}               xpath://h5[normalize-space()='Login']
