from __future__ import annotations

import random
import string
import time
from dataclasses import dataclass, asdict


@dataclass
class UserProfile:
    email: str
    first_name: str
    last_name: str
    password: str
    company: str
    address1: str
    address2: str
    city: str
    state: str
    zip_code: str
    additional_info: str
    home_phone: str
    mobile_phone: str
    alias: str


class TestDataFactory:
    """Factory keywords for generating collision-safe test data."""

    def create_unique_user_profile(self, email_domain: str = "gmail.com") -> dict:
        ts = int(time.time() * 1000)
        seed = ''.join(random.choices(string.ascii_lowercase + string.digits, k=6))
        first = f"Auto{seed[:3].title()}"
        last = f"User{seed[3:]}"

        profile = UserProfile(
            email=f"rf_{ts}_{seed}@{email_domain}",
            first_name=first,
            last_name=last,
            password=f"Test@{seed}9",
            company="AgreeYa QA Labs",
            address1=f"{random.randint(100, 999)} Main Street",
            address2="Suite 10",
            city="Noida",
            state="Alabama",
            zip_code=f"{random.randint(10000, 99999)}",
            additional_info="Generated by Robot TestDataFactory",
            home_phone=f"{random.randint(6000000000, 9999999999)}",
            mobile_phone=f"{random.randint(6000000000, 9999999999)}",
            alias=f"Home_{seed}",
        )
        return asdict(profile)
